name: SonarCloud Scan

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for proper analysis

      - name: SonarCloud Scan
        #uses: SonarSource/sonarqube-scan-action@v4.2.2
        uses: SonarSource/sonarqube-scan-action@689fb39b34b9aa95ebc5f8f119343ddd51542402
        with:
          args: >
            -Dsonar.organization=a1eko
            -Dsonar.projectKey=a1eko_treem
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          
